server:
  port: 8080

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/userRoles
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Or 'update'
      show-sql: true
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**
            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/inventory/**
            - id: user-management
              uri: lb://USER-MANAGEMENT
              predicates:
                - Path=/api/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.example.apigateway.RouteLoggingInterceptor: DEBUG
    org.springframework.cloud.gateway.server.mvc: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

    org:
      springframework:
        security: DEBUG